# Generated by Django 3.1 on 2020-08-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='title',
            field=models.CharField(default='hola', max_length=100),
            preserve_default=False,
        ),
    ]
