# Generated by Django 3.1 on 2020-09-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_meeting_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='name',
            field=models.CharField(default='hola', max_length=100),
            preserve_default=False,
        ),
    ]
